services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8011
    networks:
      - ml_network

networks:
  ml_network:
    external:
      name: ml_app_network
