services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    container_name: backend
    ports:
      - "8011:8011"
    # 👇 ADD THIS VOLUMES SECTION TO SHARE YOUR MODEL FOLDER
    volumes:
      - ./models:/models
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    container_name: frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8011
    depends_on:
      - backend
    restart: unless-stopped
